name: Release Blazor App to IIS

on:
  workflow_dispatch:

env:
  name: test

jobs:
  deploy:
    runs-on: self-hosted
    environment: test
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-app
          path: ./publish

      - name: Stop IIS App Pool
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "DefaultAppPool"
      - name: Deploy to IIS folder
        run: |
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\YourApp"
          Copy-Item -Recurse -Path ".\publish\*" -Destination "C:\inetpub\wwwroot\"
      - name: Start IIS App Pool
        run: |
          Start-WebAppPool -Name "DefaultAppPool"
