name: Deploy Stored to Test

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: "Run ID of the Build workflow to deploy"
        required: true

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Download artifact from specific Build run
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: ./app
          run-id: ${{ github.event.inputs.build_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Test
        run: |
          echo "Deploying to TEST environment"
          ls ./app
