name: Build and Release Blazor App to IIS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish
        run: dotnet publish -c Release -o ./publish
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-app
          path: ./publish

  deploy:
    runs-on: self-hosted
    needs: build
    environment: test
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-app
          path: ./publish

      - name: Deploy to IIS via WinRM
        uses: appleboy/winrm-action@v2.3.0
        with:
          host: ${{ secrets.IIS_SERVER }}
          username: ${{ secrets.IIS_USERNAME }}
          password: ${{ secrets.IIS_PASSWORD }}
          port: 5986 # Use 5985 for HTTP, 5986 for HTTPS
          protocol: https
          script: |
            Import-Module WebAdministration
            Stop-WebAppPool -Name "DefaultAppPool"
            Remove-Item -Recurse -Force "C:\inetpub\wwwroot"
            Copy-Item -Recurse -Path "${{ github.workspace }}\publish\*" -Destination "C:\inetpub\wwwroot\"
            Start-WebAppPool -Name "DefaultAppPool"
