name: Build and Release Blazor App to IIS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish
        run: dotnet publish -c Release -o ./publish
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-app
          path: ./publish

  deploy:
    runs-on: self-hosted
    needs: build
    environment: test
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-app
          path: ./publish
      - name: Stop IIS App Pool
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "DefaultAppPool"
      - name: Deploy to IIS folder
        run: |
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\YourApp"
          Copy-Item -Recurse -Path ".\publish\*" -Destination "C:\inetpub\wwwroot\"
      - name: Start IIS App Pool
        run: |
          Start-WebAppPool -Name "DefaultAppPool"
