on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish the app
        run: dotnet publish HelloWorldWeb/HelloWorldWeb.csproj -c Release -o ./publish

      - name: Install Web Deploy
        run: choco install webdeploy --no-progress
        shell: powershell

      - name: Deploy to IIS with MSDeploy
        run: |
          & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
            -verb:sync `
            -source:contentPath="publish" `
            -dest:contentPath="Default Web Site/HelloWorld",computerName="https://${{ secrets.IIS_HOSTNAME }}:8172/msdeploy.axd?site=Default Web Site", `
              userName="${{ secrets.IIS_USERNAME }}",password="${{ secrets.IIS_PASSWORD }}",authType="Basic" `
            -allowUntrusted
        shell: powershell
