name: Publish .NET 8 Blazor App

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore 

      - name: Publish
        run: dotnet publish -c Release -o ./publish
